### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by KeithGrant** [sherpal/PentagonBullets#1]
tried fastOptCompileCopy and failed with the error:
sbt.ResolveException: unresolved dependency: io.suzaku#boopickle_sjs1.0.0-M1_2.12;1.2.7-SNAPSHOT: not found
No sure which boopickle sjs version your build actually needs.
Saw a similar problem with pixi-scalajs-gui.
Thoughts?

**Comment by sherpal** [comment]
These are two similar problems related to the fact that these two libraries need to be locally pusblished.

For boopickle, you can clone the master branch here: https://github.com/suzaku-io/boopickle
Then you need to `publishLocal` it.

The other one, it's my fault, I did not put on github the pixi-scalajs-gui library that is required here. It is done now and you can find it here: https://github.com/sherpal/pixi-scalajs-gui
Again, you need to `publishLocal` it.

**Comment by KeithGrant** [comment]
Thanks Antoine, I really appreciate your quick response. I suspected the problem was related to a local version of the libraries. The pixi-scalajs-gui library you provided fixed that issue. I'm working through the boopickle build which triggered a shapeless build. Are you using the latest version of boopickle? There isn't 1.2.7 to clone, the closet is 1.2.5. Thanks again for your help.

**Comment by sherpal** [comment]
Apparently they stopped (?) putting releases and as you say, the last one is 1.2.5. However the master branch is 1.3.0. Below are the instruction to follow in order to make it work. They introduced the possibility to use scalajs 1.0.0-M1 in the 1.2.7-SNAPSHOT, but apparently broke it after, hence there is something to do. PentagonBullets however *needs* scalajs 1.0.1-M1 because of the way the JavaScript global scope works in electron's main process.

Here are the instructions (forgive me if I say stuff obvious, none of this stuff is obvious to me...):
1) Clone the boopickle master branch (currently 1.3.0)

2) in the `project/plugins.sbt` of boopickle delete the line with workbench (line 6)

3) in the `build.sbt` of boopickle, remove:
- the shapeless crossProject (lines 107 -> 123)
- the perftests crossProject (lines 157 -> 187)
- in line 191, remove the two references to shapeless (shapelessJVM and shapelessJS)

--- we are now going to publishLocal the remaining stuff ---

4) go to the boopickle filepath in the command line

5) set the SCALAJS_VERSION variable to "1.0.0-M1"
(with the instruction `set SCALAJS_VERSION=1.0.0-M1`)

6) launch sbt (if all goes according to the plan, it should resolve)

7) `publishLocal`

--- You need to re clone the PentagonBullets project ---
8) I changed the references to boopickle 1.2.7, so you need to re clone the entire PentagonBullets master branch (or, equivalently, change yourself the references of 1.2.7-SNAPSHOT in 1.3.0)


You can now resolve PentagonBullets.
Please note that when compiling, if you want to fullOptJS, you will need a massive amout of memory for java (something like 7Go). Also, you may need to fastOptJS several times in a row before it works, also because of outOfMemory issues (less serious though).

**Comment by KeithGrant** [comment]
It works! Thank you, Antoine. I wouldn’t have thought to comment out boopickle’s shapeless dependency. Great instructions and thanks for all your hard work. PentagonBullets is quite impressive.

**Comment by sherpal** [comment]
I'm glad it helps! Good luck trying to understand any of my code.
